### ISSUE TITLE
Mistake in Documentation

### ISSUE THREAD

**Issue by keiligch** [komma/komma#30]
The documentation code at [](http://komma.enilink.net/docs/#the-entity-manager-api) contains errors within the SPARQL Query:

- ``` "prefix [...] 0.1/> . " ``` must be ``` "prefix [...] 0.1/>  " ``` without the dot. 
- ``` "select ?other { ?p foaf:knows ?ther }");```  must be ``` select ?other { ?p foaf:knows ?other }");```

**Comment by kenwenzel** [comment]
Thank you for reporting this.
Are you interested in creating a fix for this?
