### ISSUE TITLE
Eclipse-market : URL not resolvable, is installation site down?

### ISSUE THREAD

**Issue by knbknb** [komma/komma#35]
Sorry, I don't know where else to post this: (I just want to check out the OWL file editor)

> Cannot install KOMMA from within Eclipse IDE, via  "Eclipse Marketplace..."  link.

The host of the update-site "dl.bintray.com" seems to be down, or even gone from the internet. At least I for one cannot connect. Neither from within Eclipse, nor by entering the domain name into a browser window.

```
nslookup dl.bintray.com
** server can't find dl.bintray.com/: NXDOMAIN

``` 

Eclipse Error

```
Error  Wed Jul 13 22:26:15 CEST 2022
Unable to read repository at https://dl.bintray.com/komma/updates/komma/1.3.2/content.xml.


eclipse.buildId=4.14.0.I20191210-0610
java.version=14.0.2
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US



```

**Comment by kenwenzel** [comment]
Bintray was shutdown last year. As I don't currently have other options for hosting the p2 site for KOMMA I stopped publishing it.
Meanwhile, you can either build the updatesite on your own via `mvn package -Pupdatesite` or use the project
https://github.com/komma/komma-ide-launch
to launch an IDE via Maven.

I'm also thinking about providing a pre-packaged IDE via Github releases.

**Comment by knbknb** [comment]
Fair enough. Thanks for the info. I do not need to try out KOMMA  that much anyway.

However I think you should also remove your stuff from Eclipse Marketplace then. Or at least add a comment to to the Marketplace entry, below the screenshots. The text that you have proided in your answer to me would be more than enough. 

Cheers, Knut
